"""New Addition to it.

Revision ID: 321c9ff8d7d5
Revises: 49456a88530d
Create Date: 2025-06-27 17:34:15.427495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321c9ff8d7d5'
down_revision = '49456a88530d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validity', sa.String(length=255), nullable=True),
    sa.Column('reachability', sa.String(length=255), nullable=True),
    sa.Column('formation', sa.String(length=255), nullable=True),
    sa.Column('dns', sa.String(length=255), nullable=True),
    sa.Column('whois', sa.String(length=255), nullable=True),
    sa.Column('ssl', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
