"""Initial Migreate

Revision ID: 49456a88530d
Revises: 
Create Date: 2025-06-25 15:54:51.438092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49456a88530d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
